#USAR_CAMARA_IP = True #CAMARA IP
USAR_CAMARA_IP = False #CAMARA LAPTOP

CAMARA_LOCAL = 0

RTSP_USUARIO = "admin"
RTSP_PASSWORD = "Udh@2025"
RTSP_IP = "192.168.22.254"
RTSP_PUERTO = 554
RTSP_CHANNEL = 1
RTSP_SUBTYPE = 0

CAMARA_WIDTH = 1280
CAMARA_HEIGHT = 720

MODELO_YOLO = "best.pt"